version: "3.7"

services:
    goldengate:
        restart: always
        build: .
        volumes:
            - .:/build
        networks:
            - nginx
        env_file:
            - ./.env
        environment:
            - PORT=5000
            - HOSTNAME=goldengate
            - NODE_ENV=production

    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
        networks:
            - nginx
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - goldengate
        depends_on:
            - goldengate


networks:
    nginx:
        driver: bridge
        